repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.6.4
    hooks:
      - id: isort
        language_version: python3.8
        additional_dependencies:
          - toml
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        language_version: python3.8

  # Run locally since pylint checks the imports
  # See: https://pre-commit.com/#repository-local-hooks
  # See: https://stackoverflow.com/a/61238571/554283
  - repo: local
    hooks:
    - id: pylint
      name: pylint
      entry: pylint
      language: system
      types: [python]
    - id: mypy
      name: mypy
      entry: mypy
      language: system
      types: [python]
