[tool.poetry]
authors = ["Frederik Peter Aalund <fpa@sbtinstruments.com>"]
description = "SBT Instruments' framework for Python-based applications"
license = "MIT"
name = "cyto"
readme = "README.md"
version = "0.1.0"

[tool.poetry.dependencies]
anyio = "^2.0.2"
pydantic = {git = "https://github.com/kozlek/pydantic.git", rev = "3d1be86e9f8d62a1566c96613500a9c19a9fd067"}
python = "^3.8"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
mypy = "^0.790"
pre-commit = "^2.8.2"
pyfakefs = "^4.2.1"
pylint = "^2.6.0"
pytest = "^6.1.2"
tox = "^3.20.1"

[build-system]
build-backend = "poetry.core.masonry.api"
requires = ["poetry-core>=1.0.0"]

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = py38, py39
requires =
    tox-poetry-dev-dependencies

[testenv]
poetry_experimental_add_locked_dependencies = true
poetry_add_dev_dependencies = true
commands =
    pytest {env:PYTEST_ARGS:}
"""

[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 88
target-version = ['py38']

[tool.isort]
# Replace with "profile = black" when we update to isort version 5
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true

[tool.pylint.master]
max-args = '7'
max-attributes = '12'
max-line-length = '88'

[tool.pylint.similarities]
ignore-imports = 'y'

[tool.pylint.'messages control']
## bad-continuation
# Let 'black' do the formatting even though the 'black' style may
# be borderline PEP8 compliant.
# See: https://github.com/psf/black/issues/1178
## wrong-import-order
# pylint, black, and isort has a compatability issue:
# https://github.com/PyCQA/pylint/issues/3722
# When this issue is resolved, we can hopefully enable
# wrong-import-order again.
disable = '''
  invalid-name,
  missing-module-docstring,
  fixme,
  bad-continuation,
  too-many-ancestors,
  wrong-import-order
'''
