[build-system]
# We can't use poetry-core, since there is a compatbility issue with
# the poetry-dynamic-versioning plug-in and tox-poetry-dev-dependencies.
build-backend = "poetry.masonry.api"
requires = ["poetry>=1.0.0", "poetry-dynamic-versioning"]

[tool.poetry]
authors = ["Frederik Peter Aalund <fpa@sbtinstruments.com>"] 
description = "SBT Instruments' framework for Python-based applications" 
license = "MIT" 
name = "cyto" 
readme = "README.md" 
version = "0.0.0" # Placeholder (we use the poetry-dynamic-versioning plug-in)

[tool.poetry.dependencies]
anyio = "^2.0.2"
pydantic = {git = "https://github.com/kozlek/pydantic.git", rev = "3d1be86e9f8d62a1566c96613500a9c19a9fd067"}
python = "^3.8"
toml = "^0.10.2"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
isort = "^5.6.4"
mypy = "^0.790"
pre-commit = "^2.8.2"
pyfakefs = "^4.2.1"
pylint = "^2.6.0"
pytest = "^6.1.2"
pytest-cov = "^2.10.1"
taskipy = "^1.4.0"

[tool.poetry-dynamic-versioning]
enable = true

[tool.taskipy.tasks]
black = "black cyto tests"
coverage = "pytest --cov=cyto --cov-fail-under=95"
isort = "isort cyto tests"
mypy = "mypy cyto tests"
pre-commit = "pre-commit run --all-files"
pylint = "pylint cyto tests"

[tool.tox]
legacy_tox_ini = """
[tox]
isolated_build = true
envlist = clean,py38,py39,coverage
requires =
    tox-poetry-dev-dependencies

[testenv]
poetry_experimental_add_locked_dependencies = true
poetry_add_dev_dependencies = true
depends =
    {py38,py39}: clean
    coverage: py38, py39
commands =
    pytest --cov=cyto --cov-append --cov-report=term-missing {env:PYTEST_ARGS:}

[testenv:clean]
basepython = python3.8
skip_install = true
commands = coverage erase

[testenv:coverage]
basepython = python3.8
skip_install = true
commands =
    coverage html --precision=2
    coverage report --precision=2 --fail-under=98
"""

[tool.black]
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | _build
  | buck-out
  | build
  | dist
)/
'''
include = '\.pyi?$'
line-length = 88
target-version = ['py38']

[tool.isort]
# Replace with "profile = black" when we update to isort version 5
ensure_newline_before_comments = true
force_grid_wrap = 0
include_trailing_comma = true
line_length = 88
multi_line_output = 3
use_parentheses = true

[tool.pylint.master]
max-args = '7'
max-attributes = '12'
max-line-length = '88'

[tool.pylint.similarities]
ignore-imports = 'y'

[tool.pylint.'messages control']
## bad-continuation
# Let 'black' do the formatting even though the 'black' style may
# be borderline PEP8 compliant.
# See: https://github.com/psf/black/issues/1178
## wrong-import-order
# pylint, black, and isort has a compatability issue:
# https://github.com/PyCQA/pylint/issues/3722
# When this issue is resolved, we can hopefully enable
# wrong-import-order again.
disable = '''
  invalid-name,
  missing-module-docstring,
  fixme,
  bad-continuation,
  too-many-ancestors,
  wrong-import-order
'''
